apiVersion: v1
kind: Service
metadata:
  name: cb-java-hello-world
spec:
  type: NodePort
  selector:
    app: cb-java-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30725