apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-java-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-java-hello-world
  template:
    metadata:
      labels:
        app: cb-java-hello-world
    spec:
      containers:
        - name: cb-java-hello-world
          image: gcr.io/high-hue-237416/cb-java-hello-world:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"